### ISSUE TITLE
Multiple exceptions in IE when using a codelens provider

### ISSUE THREAD

**Issue by foxable** [Microsoft/monaco-editor#1004]
monaco-editor version: 0.14.2
Browser: IE 11
OS: Windows 10

Steps or JS usage snippet reproducing the issue:

1. Open the [Codelens provider example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example) from the Playground in IE 11
2. The expected codelens does not appear in the first line. Instead, the exceptions listed below occur.
3. Further exceptions occur when trying to trigger the IntelliSense widget using Ctrl + Space.

```
TypeError: Unable to get property 'length' of undefined or null reference
   at e.prototype._renderCodeLensSymbols (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1567:923)
   at Anonymous function (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1566:435)
   at t (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:210:605)
   at g (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:119:180)
   at P.enter (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:122:536)
   at _run (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:124:387)
   at _completed (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:123:847)
   at Anonymous function (https://microsoft.github.io/monaco-editor/
```

```
TypeError: Unable to get property 'map' of undefined or null reference
   at e.prototype.updateDecorations (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1207:529)
   at Anonymous function (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1207:144)
   at t (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:210:605)
   at g (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:119:180)
   at P.enter (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:122:536)
   at _run (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:124:387)
   at _completed (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:123:847)
   at Anonymous function (https://microsoft.github.io/monaco-editor/node_mod
```

**Comment by kpreisser** [comment]
Hi,

the issue with the **IntelliSense widget** not working in **IE 11** in Monaco Editor 0.14.3 also occurs when using a TypeScript document; e.g. if you simply open https://microsoft.github.io/monaco-editor/ in IE and in the TypeScript code press Ctrl + Space on any line.

Additionally, other widgets like "Find all References" are not working in IE.

This currently blocks us from updating the Monaco Editor in our product, because we still have to use the WebBrowser control in .NET that uses IE.

Thanks!

**Comment by blutorange** [comment]
It was not working for me in IE as well. I did investigate for a bit and found that the promise polyfill used by vscode has a bug with chaining: https://github.com/Microsoft/vscode/issues/57722 (now fixed).

Not certain if this is the same issue, but it was working in IE11 for me after I added a different promise polyfill.

**Comment by alexandrudima** [comment]
I have just tried, and this is fixed on master
