### ISSUE TITLE
IE11 Intellisense broken

### ISSUE THREAD

**Issue by sbuchok** [Microsoft/monaco-editor#1110]
Using IE11 goto https://microsoft.github.io/monaco-editor/ 
In the example go to line 7
Press ctrl + space
Loading... comes up then nothing

This is not the same issue as https://github.com/Microsoft/monaco-editor/issues/96

There is an error in the dev tool bar:

SCRIPT5007: Unable to get property 'length' of undefined or null reference
completionModel.ts (154,9)
SCRIPT5022: Unable to get property 'length' of undefined or null reference

TypeError: Unable to get property 'length' of undefined or null reference
   at e.prototype._createCachedState (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:795:733)
   at e.prototype._ensureCachedState (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:795:436)
   at items.get (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:794:777)
   at e.prototype._onNewContext (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1282:966)
   at Anonymous function (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:1282:308)
   at t (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:210:605)
   at g (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:119:180)
   at P.enter (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:122:536)
   at _run (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:124:387)
   at _completed (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:123:847)
errors.ts (75,6)

Pretty sure I'm using latest IE11
Version: 11.345.17134.0

**Comment by sbuchok** [comment]
Sorry, should also say, at the time of this ticket, the demo site seems to be using 0.14.3

**Comment by sbuchok** [comment]
Sorry, duplicate of https://github.com/Microsoft/monaco-editor/issues/1004
