### ISSUE TITLE
Cannot call a namespace ('marked')

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/monaco-editor#1183]
**monaco-editor version:** 0.15.1
**Browser:** none (build error)
**OS:** Windows 7

I have encountered an build error in monaco when I'm upgrading Monaco editor to the latest one.

```
[!] Error: Cannot call a namespace ('marked')
node_modules\monaco-editor\esm\vs\base\browser\htmlContentRenderer.js (147:24)
145:         renderer: renderer
146:     };
147:     element.innerHTML = marked(markdown.value, markedOptions);
                             ^
148:     signalInnerHTML();
149:     return element;
Error: Cannot call a namespace ('marked')
    at error (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:3460:30)
    at Module.error (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:13358:9)
    at CallExpression.bind (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:10228:30)
    at AssignmentExpression.NodeBase.bind (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:9183:23)
    at AssignmentExpression.bind (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:9919:31)
    at ExpressionStatement$$1.NodeBase.bind (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:9183:23)
    at BlockStatement$$1.NodeBase.bind (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:9179:31)
    at FunctionDeclaration$$1.NodeBase.bind (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:9183:23)
    at ExportNamedDeclaration.bind (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:10641:30)
    at Program.NodeBase.bind (C:\Users\t-nagashima.AD\dev\vue-eslint-editor\node_modules\rollup\dist\rollup.js:9179:31)
```

The problematic code is:

```js
import * as marked from '../common/marked/marked.js';
// ....
     element.innerHTML = marked(markdown.value, markedOptions);
```

In my understanding, we cannot call the binding of namespace imports because it's a [Module Namespace Object](https://www.ecma-international.org/ecma-262/9.0/#sec-module-namespace-objects). `monaco-editor@0.14.3` doesn't have this kind of problem.

**Steps or JS usage snippet reproducing the issue:**

1. `git clone -b upgrade-monaco-editor https://github.com/mysticatea/vue-eslint-editor.git`
2. `cd vue-eslint-editor`
3. `npm install`
4. `npm run -s build`

**Comment by mysticatea** [comment]
Thank you so much!
