### ISSUE TITLE
Unhandled Exception: TypeError: Unable to get property 'replace' of undefined or null reference

### ISSUE THREAD

**Issue by nojvek** [Microsoft/monaco-editor#122]
After updating to a new version of monaco in F12, I am getting lots of unhandled exceptions coming out from Monaco.

I haven't been able to get a consistent repro, but when our tests run, this fires up as the noisiest unhandled exception.

```
TypeError: Unable to get property 'replace' of undefined or null reference
   at ViewLineToken (common/monaco-editor/min/vs/editor/editor.main.js:9831:13)
   at TokensBinaryEncoding.inflateArr (common/monaco-editor/min/vs/editor/editor.main.js:20279:17)
   at LineTokens.prototype.inflate (common/monaco-editor/min/vs/editor/editor.main.js:20948:13)
   at IdentityFilteredLineTokens.create (common/monaco-editor/min/vs/editor/editor.main.js:14623:13)
   at IdentitySplitLine.prototype.getOutputLineTokens (common/monaco-editor/min/vs/editor/editor.main.js:44836:13)
   at SplitLinesCollection.prototype.getOutputLineTokens (common/monaco-editor/min/vs/editor/editor.main.js:45301:13)
   at ViewModel.prototype.getLineTokens (common/monaco-editor/min/vs/editor/editor.main.js:49187:13)
   at ViewLine.prototype.shouldUpdateHTML (common/monaco-editor/min/vs/editor/editor.main.js:33013:17)
   at ViewLayerRenderer.prototype._finishRendering (common/monaco-editor/min/vs/editor/editor.main.js:46304:17)
   at ViewLayerRenderer.prototype._render (common/monaco-editor/min/vs/editor/editor.main.js:46182:13)
editor.main.js (15303,1)
```

The issue line seems to be this:

```
at ViewLineToken 
        function ViewLineToken(startIndex, type) { // type is not defined
            this.startIndex = startIndex | 0; // @perf
            this.type = type.replace(/[^a-z0-9\-]/gi, ' ');
        }

at TokensBinaryEncoding.inflateArr 
        TokensBinaryEncoding.inflateArr = function (map, binaryEncodedTokens) {
            if (binaryEncodedTokens.length === 0) {
                return INFLATED_TOKENS_EMPTY_TEXT;
            }
            if (binaryEncodedTokens.length === 1 && binaryEncodedTokens[0] === 0) {
                return INFLATED_TOKENS_NON_EMPTY_TEXT;
            }
            var result = [];
            var inflateMap = map._inflate;
            for (var i = 0, len = binaryEncodedTokens.length; i < len; i++) {
                var deflated = binaryEncodedTokens[i];
                var startIndex = (deflated / START_INDEX_OFFSET) & START_INDEX_MASK;
                var deflatedType = (deflated / TYPE_OFFSET) & TYPE_MASK;
                result.push(new viewLineToken_1.ViewLineToken(startIndex, inflateMap[deflatedType])); // deflatedType is not present in inflateMap
            }
            return result;
        };
```

I don't know enough about monaco internals on what would be the ideal fix. A quick fix would be to add a null guard to ViewLineToken but not sure what the impact would be. 

@alexandrudima , @roblourens suggestions?

**Comment by roblourens** [comment]
Hey Noj, I couldn't figure it out when I was investigating. From what I remember, I was only seeing it when F12 started up, when the first document loaded is html.

I didn't have time to create a standalone repro, but if you're able to do that, you could try creating a page with just Monaco, that loads some text that makes this error show up. F12 loads the doc in chunks and calls `applyEdits` to append the chunks, so maybe there's a bug involving calling that api many times quickly with incomplete chunks of an html doc.

**Comment by nojvek** [comment]
Oh cool thanks. Will take a look at applyChunks.

**Comment by alexandrudima** [comment]
I could reproduce with the following snippet:

```
loadEditor(function() {
		var editor = monaco.editor.create(document.getElementById('Editor'), {
			value: '',
			language: 'html'
		});
		var text = document.documentElement.innerHTML.replace(/></g, '>\n<');
		function rand(max) {
			return Math.floor(Math.random() * max) + 1
		}

		function update() {
			var offset = rand(Math.min(10000, text.length));
			var prefix = text.substr(0, offset);
			text = text.substr(offset);

			var model = editor.getModel();
			let editOp = {
				range: new monaco.Range(model.getLineCount(), model.getLineMaxColumn(model.getLineCount()), model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
				text: prefix
			};
			model.applyEdits([editOp]);
			editor.setPosition(new monaco.Position(model.getLineCount(), model.getLineMaxColumn(model.getLineCount())));
			editor.revealPosition(new monaco.Position(model.getLineCount(), model.getLineMaxColumn(model.getLineCount())));

			if (text.length > 0) {
				setTimeout(update, 1000);
			}
		}

		update();
	});
```

**Comment by nojvek** [comment]
Wow this was fast. Thanks Alexandru.

When will monaco-editor update with the new changes?

**Comment by alexandrudima** [comment]
We plan to create the August release sometime this week, next week at the latest...

**Comment by roblourens** [comment]
@nojvek - F12 was using a custom build, not the monaco-editor package, so you could try it out any time. You probably want to wait for the next stable release. Previous bits were based off the 1.4 tag.

**Comment by nojvek** [comment]
No problem. Will wait for 1.4
