### ISSUE TITLE
Error: Cannot read property 'modeId' of undefined

### ISSUE THREAD

**Issue by jrieken** [Microsoft/monaco-editor#133]
* have all monaco-xyz things setup locally for development
* open the smoke-test page: http://localhost:8080/monaco-editor/test/smoketest.html?editor=dev&monaco-typescript=dev&monaco-css=dev&monaco-json=dev&monaco-languages=dev
* run the `multi cursor` command
* 💥 these errors shown on the console:

```
errors.js:14 Uncaught Error: Cannot read property 'modeId' of undefined

TypeError: Cannot read property 'modeId' of undefined
    at Model.TextModelWithTokens._findMatchingBracketUp (http://localhost:8080/vscode/out/vs/editor/common/model/textModelWithTokens.js:685:33)
    at Model.TextModelWithTokens._matchFoundBracket (http://localhost:8080/vscode/out/vs/editor/common/model/textModelWithTokens.js:676:36)
    at Model.TextModelWithTokens._matchBracket (http://localhost:8080/vscode/out/vs/editor/common/model/textModelWithTokens.js:656:42)
    at Model.TextModelWithTokens.matchBracket (http://localhost:8080/vscode/out/vs/editor/common/model/textModelWithTokens.js:596:25)
    at OneCursor.adjustBracketDecorations (http://localhost:8080/vscode/out/vs/editor/common/controller/oneCursor.js:112:43)
    at CursorCollection.normalize (http://localhost:8080/vscode/out/vs/editor/common/controller/cursorCollection.js:122:42)
    at Cursor._createAndInterpretHandlerCtx (http://localhost:8080/vscode/out/vs/editor/common/controller/cursor.js:200:26)
    at Cursor._onHandler (http://localhost:8080/vscode/out/vs/editor/common/controller/cursor.js:218:48)
    at Cursor.trigger (http://localhost:8080/vscode/out/vs/editor/common/controller/cursor.js:722:18)
    at StandaloneEditor.CommonCodeEditor.trigger (http://localhost:8080/vscode/out/vs/editor/common/commonCodeEditor.js:420:29)
```

**Comment by alexandrudima** [comment]
From debugging it looks like this error is happening in the `vb` editor

**Comment by alexandrudima** [comment]
From further debugging this reproduces by simply clicking on line 5 in this `vb` file:

```vb
vb
Imports System
Imports System.Collections.Generic

Module Module1

    Sub Main()
        Dim a As New M8Ball

        Do While True

            Dim q As String = ""
            Console.Write("ask me about the future... ")
            q = Console.ReadLine()

            If q.Trim <> "" Then
                Console.WriteLine("the answer is... {0}", a.getAnswer(q))
            Else
                Exit Do
            End If
        Loop

    End Sub

End Module

Class M8Ball

    Public Answers As System.Collections.Generic.Dictionary(Of Integer, String)

    Public Sub New()
        Answers = New System.Collections.Generic.Dictionary(Of Integer, String)
        Answers.Add(0, "It is certain")
        Answers.Add(1, "It is decidedly so")
        Answers.Add(2, "Without a doubt")
        Answers.Add(3, "Yes, definitely")
        Answers.Add(4, "You may rely on ")
        Answers.Add(5, "As I see it, yes")
        Answers.Add(6, "Most likely")
        Answers.Add(7, "Outlook good")
        Answers.Add(8, "Signs point to yes")
        Answers.Add(9, "Yes")
        Answers.Add(10, "Reply hazy, try again")
        Answers.Add(11, "Ask again later")
        Answers.Add(12, "Better not tell you now")
        Answers.Add(13, "Cannot predict now")
        Answers.Add(14, "Concentrate and ask again")
        Answers.Add(15, "Don't count on it")
        Answers.Add(16, "My reply is no")
        Answers.Add(17, "My sources say no")
        Answers.Add(18, "Outlook not so")
        Answers.Add(19, "Very doubtful")
    End Sub

    Public Function getAnswer(theQuestion As String) As String
        Dim r As New Random
        Return Answers(r.Next(0, 19))
    End Function

End Class
```

**Comment by alexandrudima** [comment]
Ok, final better steps: Open http://localhost:8080/monaco-editor/test/?editor=dev#sample - vb

Click on line 4 `Module`
