### ISSUE TITLE
Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'

### ISSUE THREAD

**Issue by wind-hx** [microsoft/monaco-editor#1733]
Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at resolveMonacoPath (/Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.8.1@monaco-editor-webpack-plugin/out/index.js:26:20)
    at use.options.pre.featurePaths.map (/Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.8.1@monaco-editor-webpack-plugin/out/index.js:161:63)
    at Array.map (<anonymous>)
    at createLoaderRules (/Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.8.1@monaco-editor-webpack-plugin/out/index.js:161:43)
    at MonacoEditorWebpackPlugin.apply (/Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.8.1@monaco-editor-webpack-plugin/out/index.js:80:23)
    at Compiler.apply (/Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_tapable@0.2.9@tapable/lib/Tapable.js:375:16)
    at webpack (/Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_webpack@3.12.0@webpack/lib/webpack.js:33:19)
    at err (/Volumes/wind_ssd/project/web-project/ems-user-web/build/build.js:24:3)
    at next (/Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:83:7)
    at CB (/Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:119:9)
    at /Volumes/wind_ssd/project/web-project/ems-user-web/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:145:14
    at FSReqWrap.oncomplete (fs.js:153:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ems-user-web@1.0.0 build:prod: `cross-env NODE_ENV=production node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ems-user-web@1.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wind/.npm/_logs/2019-12-25T13_45_44_287Z-debug.log

**monaco-editor version:** 0.17.1
**Browser: chrome**
**OS: macos**
**Playground code that reproduces the issue:**

```js
npm run build
```

**Comment by yunliang-ding** [comment]
Try to upgrade "monaco-editor-webpack-plugin": "1.8.1"

**Comment by yunliang-ding** [comment]
Attempt to upgrade "monaco-editor": "0.19.0"
