### ISSUE TITLE
Clicking on error related to "default" throws "Cannot read property 'parent' of undefined"

### ISSUE THREAD

**Issue by gergzk** [microsoft/monaco-editor#1751]
For the special case of the keyword default in a typescript piece of code (see example), clicking on 'default' throws the below error:

```ts
/// code starts here 
default

async function main() {
   // function body here
}
/// code ends here
```

```
Uncaught Error: Cannot read property 'parent' of undefined

TypeError: Cannot read property 'parent' of undefined
    at i (<ourdomain>/external/monaco-editor-0-17-0/min/vs/language/typescript/tsWorker.js:7:1658543)
    at Object.getDocumentHighlights (<ourdomain>/external/monaco-editor-0-17-0/min/vs/language/typescript/tsWorker.js:7:1660113)
    at t (<ourdomain>/external/monaco-editor-0-17-0/min/vs/language/typescript/tsWorker.js:7:2005942)
    at Object.getOccurrencesAtPosition (<ourdomain>/external/monaco-editor-0-17-0/min/vs/language/typescript/tsWorker.js:7:2011337)
    at t.getOccurrencesAtPosition (<ourdomain>/external/monaco-editor-0-17-0/min/vs/language/typescript/tsWorker.js:7:3066932)
    at t.fmr (<ourdomain>/external/monaco-editor-0-17-0/min/vs/base/worker/workerMain.js#typescript:142:47)
    at e._handleMessage (<ourdomain>/external/monaco-editor-0-17-0/min/vs/base/worker/workerMain.js#typescript:89:195)
    at Object.handleMessage (<ourdomain>/external/monaco-editor-0-17-0/min/vs/base/worker/workerMain.js#typescript:88:700)
    at e._handleMessage (<ourdomain>/external/monaco-editor-0-17-0/min/vs/base/worker/workerMain.js#typescript:86:897)
    at e.handleMessage (<ourdomain>/external/monaco-editor-0-17-0/min/vs/base/worker/workerMain.js#typescript:86:465)
```

**Comment by alexdima** [comment]
I believe this is an issue with TypeScript itself and have created https://github.com/microsoft/TypeScript/issues/36023 .
