### ISSUE TITLE
Access references between two or more models via 'Go to Definition', 'Peek Definition' or 'Find All References'

### ISSUE THREAD

**Issue by gujiman** [Microsoft/monaco-editor#217]
monaco-editor npm version: 0.6.1
Browser: Chrome
OS: Windows 7

I'm trying to create a really basic example of how to create multiple models (monaco.editor.createModel).
In my example i have:

var model1 = monaco.editor.createModel("function hello1() {\n\talert('aaaaa!');\n}\nhello1();\n\nhello2();", "javascript");
var model2 = monaco.editor.createModel("function hello2() {\n\talert('bbbbb!');\n}", "javascript");
var  editor = monaco.editor.create(document.getElementById("container"));
editor.setModel(model1);

I have managed to setup the code so that i can toggle between the 2 models.

However when I want to "Go to Definition" of a function (hello2) that is referenced in model1 but defined in model2, then i get the following error message:

WARNING: Promise with no error callback:2
Object {exception: TypeError: Cannot read property 'getControl' of null
    at http://127.0.0.1/monac…, error: null, promise: ExceptionPromise_ctor, handler: undefined, id: 2…}error: nullexception: TypeError: Cannot read property 'getControl' of null
    at http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:82465:30
    at CompletePromise_ctor.CompletePromise_then [as then] (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:8425:49)
    at GoToDefinitionAction.DefinitionAction._openReference (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:82464:28)
    at GoToDefinitionAction.DefinitionAction._onResult (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:82449:22)
    at http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:82435:30
    at Object.notifySuccess [as _notify] (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:8029:59)
    at Object.enter (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:7711:30)
    at Promise_ctor._run (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:7927:29)
    at Promise_ctor._completed (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:7895:18)
    at argDone (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:8672:37)handler: undefinedid: 2parent: undefinedpromise: ExceptionPromise_ctor__proto__: Object
TypeError: Cannot read property 'getControl' of null
    at goToDeclaration.ts:127
    at CompletePromise_ctor.CompletePromise_then [as then] (winjs.base.raw.js:1566)
    at GoToDefinitionAction.DefinitionAction._openReference (goToDeclaration.ts:126)
    at GoToDefinitionAction.DefinitionAction._onResult (goToDeclaration.ts:110)
    at goToDeclaration.ts:96
    at Object.notifySuccess [as _notify] (winjs.base.raw.js:1170)
    at Object.enter (winjs.base.raw.js:852)
    at Promise_ctor._run (winjs.base.raw.js:1068)
    at Promise_ctor._completed (winjs.base.raw.js:1036)
    at argDone (winjs.base.raw.js:1813)
Uncaught Error: Cannot read property 'getControl' of null

TypeError: Cannot read property 'getControl' of null
    at http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:82465:30
    at CompletePromise_ctor.CompletePromise_then [as then] (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:8425:49)
    at GoToDefinitionAction.DefinitionAction._openReference (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:82464:28)
    at GoToDefinitionAction.DefinitionAction._onResult (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:82449:22)
    at http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:82435:30
    at Object.notifySuccess [as _notify] (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:8029:59)
    at Object.enter (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:7711:30)
    at Promise_ctor._run (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:7927:29)
    at Promise_ctor._completed (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:7895:18)
    at argDone (http://127.0.0.1/monaco/0.6.1/monaco-editor/dev/vs/editor/editor.main.js:8672:37)

**Comment by gujiman** [comment]
Got it to work!

You can toggle between 2 or more models and use 'Go to Definition', 'Peek Definition' or 'Find All References'.

Check out:

https://github.com/gujiman/0.7.0
