### ISSUE TITLE
Multiple errors reported by Sentry

### ISSUE THREAD

**Issue by vtanciks** [microsoft/monaco-editor#2399]
I have the latest version of monaco-editor installed used with React wrapper, and it's working as expected when we test it.  But when it used in production, we get lots of handled and unhandled errors logged by Sentry: 

```
TypeError: Cannot read property 'parent' of undefined
    at bT (https://cdn.jsdelivr.net/npm/monaco-editor@0.22.3/min/vs/language/typescript/tsWorker.js:21:1520827)

RangeError: Maximum call stack size exceeded
    at u (https://cdn.jsdelivr.net/npm/monaco-editor@0.22.3/min/vs/language/typescript/tsWorker.js:21:770316)

Canceled canceled(npm/monaco-editor@0.22.3/min-maps/vs/editor/vs/editor/file:/Users/alex/src

TypeError: Cannot read property 'kind' of undefined
    at Object.e.isNewExpression (https://cdn.jsdelivr.net/npm/monaco-editor@0.22.3/min/vs/language/typescript/tsWorker.js:21:730631)
```

I don't have clear ways of reproducing those errors, but we get them reported every day.

OS: WIndows 10
Browser: Chrome 89
monaco-editor version 0.22.3

**Comment by shubhendusaurabh** [comment]
facing same problem.

for now using workaround mentioned in #2382

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/monaco-editor/issues/2382
