### ISSUE TITLE
TypeError: _monacoEditorCore.Emitter is not a constructor with Jest

### ISSUE THREAD

**Issue by abhishekthakurak** [microsoft/monaco-editor#2513]
**monaco-editor version: 0.24.0**
**monaco-editor-webpack-plugin: 3.1.0**
**OS: macOS catalina**
**ts-jest: 26.5.6**
**jest: 26.6.3**

I have upgraded monaco editor from [0.20.0 TO 0.24.0] and monaco-editor-webpack-plugin [1.9.0 TO 3.1.0]
my test cases are failing which is running perfectly on 0.20.0.

please let me know what i am doing wrong!

    Test suite failed to run

    TypeError: _monacoEditorCore.Emitter is not a constructor

      1 | //lib
    > 2 | import * as monaco from 'monaco-editor';
        | ^
      3 | import _map from 'lodash/map';
      4 |
      5 | //utils

      at new LanguageServiceDefaultsImpl (../../node_modules/monaco-editor/esm/vs/language/typescript/monaco.contribution.js:56:29)
      at Object.<anonymous> (../../node_modules/monaco-editor/esm/vs/language/typescript/monaco.contribution.js:196:33)
      at Object.<anonymous> (../../node_modules/monaco-editor/esm/vs/editor/editor.main.js:1:1)
      at Object.<anonymous> (src/space-app/components/advanceQuery/hooks/useAdvanceQueryMonacoEditor/helpers/suggestionResponseHelper.ts:2:1)
      at Object.<anonymous> (src/space-app/components/advanceQuery/hooks/useAdvanceQueryMonacoEditor/helpers/suggestionProvider.ts:23:1)
      at Object.<anonymous> (src/space-app/components/advanceQuery/hooks/useAdvanceQueryMonacoEditor/helpers/__tests__/suggestionProvider.spec.ts:2:1)` 

my jest config
```js
/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable global-require */
const defaultConfigCreator = require('../../jest.base.config');

const defaultMainWebConfig = defaultConfigCreator.getConfig(require('./package.json'));

module.exports = {
  ...defaultMainWebConfig,
  setupFiles: [...defaultMainWebConfig.setupFiles, './test/jest/index.js'],
  transform: {
    ...defaultMainWebConfig.transform,
    '^.+\\.html$': './test/jest/transformers/jest.ejx-transformer.js',
  },
  modulePaths: [
    ...defaultMainWebConfig.modulePaths,
    'test',
    '<rootDir>/src/',
    '<rootDir>/',
    '<rootDir>/../modules/src',
    '<rootDir>/../',
  ],
  moduleNameMapper: {
  ...
  },
  transformIgnorePatterns: [
    'node_modules/(?!spr-web-components|spr-base|spr-social-previews|spr-email-web-components|monaco-editor)',
  ],
  testPathIgnorePatterns: ['node_modules/', '/lib/'],
};

```

**Comment by hediet** [comment]
Thanks for reporting this issue! Can you provide a minimal reproducable example, so we can debug it (as git repo)?

**Comment by abhishekthakurak** [comment]
@hediet i will try to create such repo and add the link

**Comment by hediet** [comment]
Closing due to inactivity.

If this bug still applies, please create a new issue. Make sure to select the form for bugs and include a minimal reproducible example. Thanks!
