### ISSUE TITLE
Cannot read property 'addEventHandler' of undefined

### ISSUE THREAD

**Issue by islegare** [microsoft/monaco-editor#2641]
**monaco-editor version:** 0.22.3
**Browser:** Chrome 92.0
**OS:** Windows 10
**Playground code that reproduces the issue:** Can't repro

We found the following error in the telemetry of our production code:
```
TypeError: TypeError: Cannot read property 'addEventHandler' of undefined
    at addEventHandler (../../../node_modules/monaco-editor/esm/vs/editor/browser/view/viewPart.js:11:22)
    at construct (../../../node_modules/@babel/runtime/helpers/esm/createSuper.js:12:23)
    at new n (../../../node_modules/monaco-editor/esm/vs/editor/browser/viewParts/editorScrollbar/editorScrollbar.js:12:8)
    at new n (../../../node_modules/monaco-editor/esm/vs/editor/browser/view/viewImpl.js:75:26)
    at n.value (../../../node_modules/monaco-editor/esm/vs/editor/browser/widget/codeEditorWidget.js:1159:21)
    at _createView (../../../node_modules/monaco-editor/esm/vs/editor/browser/widget/codeEditorWidget.js:1080:41)
    at n.value (../../../node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneCodeEditor.js:187:8)
    at _attachModel (../../../node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneCodeEditor.js:167:13)
    at callback (../../../node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneEditor.js:49:17)
```

We haven't been able to reproduce this code locally, and we can't figure out why it would occur in editorScrollbar as opposed to an earlier case in which the ViewContext is utilized.

**Comment by islegare** [comment]
Please let me know what additional information is needed, and I will attempt to do provide it. If it's just a matter of adding repro steps, then there isn't much I can do.

**Comment by alexdima** [comment]
Yes, I'm sorry but the stack does not make sense to me. In the past, I have seen some uglifiers mess up the sourcemap or the actual code, but as it is right now, this issue is not actionable.
