### ISSUE TITLE
[Bug] HTML language does not recognize inline <script type="module"> as JavaScript

### ISSUE THREAD

**Issue by Yoplitein** [microsoft/monaco-editor#2962]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
	value: `<script type="module">\n\tconsole.log("hello");\n</script>`,
	language: 'html'
});
```

### Actual Behavior

The contents of the script tag are marked as language `vs.editor.nullLanguage`, precluding highlighting and causing various callbacks for editor features to throw `Unexpected languageId` upon calling `LanguageConfigurationRegistry.getLanguageConfiguration`.

### Expected Behavior

Inline code is recognized as JavaScript, is syntax highlighted, and editing/navigation does not raise exceptions.

### Additional Context

This began causing exceptions in version 0.32.0, with 0.31.1 and prior nothing is raised but the inline code is still similarly marked as `vs.editor.nullMode`.

**Comment by hediet** [comment]
I can reproduce. It seems like `type="module"` tokenizes the content as language `module`, which does not exist - thus the error. `type="html"`or `type="css"` works as expected.

**Comment by cetinsert** [comment]
Interestingly, `type=module` (no quotes) works just fine!

![image](https://user-images.githubusercontent.com/27027/157737526-c58988bb-3412-4a51-8992-a903f2dea9bd.png)

**Comment by hediet** [comment]
We fixed this in vscode. The next monaco editor version will be released soon.

**Comment by Delagen** [comment]
0.34.0 has this issue also
```
<script type="text/javascript">
var qd = {};
</script>
```
Any click inside script tag produce

![image](https://user-images.githubusercontent.com/783335/189311369-62506699-aeb8-45b2-801c-24a8eaeaad6a.png)

**Comment by jonatanklosko** [comment]
Same with Markdown, when annotating a code code block with unknown language:

````
```mermaid
graph TD;
  A-->B;
  A-->C;
  B-->D;
  C-->D;
```
````

Error:

```
errors.ts:21 Uncaught Error: Language id "vs.editor.nullLanguage" is not configured nor known

Error: Language id "vs.editor.nullLanguage" is not configured nor known
    at f (languageConfigurationRegistry.ts:130:10)
    at c.getLanguageConfiguration (languageConfigurationRegistry.ts:113:13)
    at u.getLanguageConfiguration (tokenizationTextModelPart.ts:329:45)
    at u.getWordAtPosition (tokenizationTextModelPart.ts:350:9)
    at Ot.getWordAtPosition (textModel.ts:1860:42)
    at F._getWord (wordHighlighter.ts:355:21)
    at F._run (wordHighlighter.ts:373:21)
    at F._onPositionChanged (wordHighlighter.ts:347:8)
    at wordHighlighter.ts:224:9
    at t.invoke (event.ts:607:17)
    at errors.ts:26:12
```

(reproduced on the https://microsoft.github.io/monaco-editor playground).

**Comment by pansinm** [comment]
1. reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)
```js
monaco.editor.create(document.getElementById('container'), {
	value: "```notsupport\nerror when press enter\n```",
	language: 'markdown'
});
```
2. solve this problem
```js
monaco.languages.register({id: 'vs.editor.nullLanguage'})
monaco.languages.setLanguageConfiguration('vs.editor.nullLanguage', {})

monaco.editor.create(document.getElementById('container'), {
	value: "```notsupport\nerror when press enter\n```",
	language: 'markdown'
});
```

**Comment by hediet** [comment]
> Error: Language id "vs.editor.nullLanguage" is not configured nor known

This will be fixed with the next release of the monaco editor.

> Inline code is recognized as JavaScript, is syntax highlighted,

This is the remaining feature request of this issue.

**Comment by silverwind** [comment]
Was this fix released?

**Comment by silverwind** [comment]
Tested https://github.com/microsoft/monaco-editor/issues/2962#issuecomment-1301587105 in playground, the error is present in 0.34.1 and gone in 0.35.0.

**Comment by CetinSert** [comment]
I have just tested this again:
- ❌ [`0.33.0`](https://microsoft.github.io/monaco-editor/playground.html?source=v0.33.0#XQAAAAKJAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzncHRgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKigSJIWy-GtxEfSHC7r77gqAcJKWlXiqbuVzMKXtVytgkZl1A8_rxfFXvchsKQPJyu9iMEEIRDcywPrSaQJJ4jIG8msz8cSwb-E1AGnvoKBzA61s8b71sOyArj4hp3x5pfdD7H2DsfBvcIcl5wDaGlcyujj8eLTL47HjTRHKDOKdlWKOUWzg9S8hJBSxJswNT4Hhp1Po7wGUS5KqBZOm-CfmEwwEz58LZ3_TYMHk8d8VT0P210OM)
- ✔ [`0.34.0`](https://microsoft.github.io/monaco-editor/playground.html?source=v0.34.0#XQAAAAKJAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzncHRgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKigSJIWy-GtxEfSHC7r77gqAcJKWlXiqbuVzMKXtVytgkZl1A8_rxfFXvchsKQPJyu9iMEEIRDcywPrSaQJJ4jIG8msz8cSwb-E1AGnvoKBzA61s8b71sOyArj4hp3x5pfdD7H2DsfBvcIcl5wDaGlcyujj8eLTL47HjTRHKDOKdlWKOUWzg9S8hJBSxJswNT4Hhp1Po7wGUS5KqBZOm-CfmEwwEz58LZ3_TYMHk8d8VT0P210OM)

**Comment by PaperPrototype** [comment]
Is this solved?
