### ISSUE TITLE
[Bug] The sample browser-esm-parcel is not working

### ISSUE THREAD

**Issue by ashleydavis** [microsoft/monaco-editor#2966]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
The sample browser-esm-parcel is not working.

Steps to reproduce:


git clone git@github.com:microsoft/monaco-editor.git
cd monaco-editor
cd samples/browser-esm-parcel
npm install
npm start


Open browser to http://localhost:1234/ to view the web page served Parcel's dev server.

Open the dev console.
```

### Actual Behavior

An empty box appears in the web page where the Monaco Editor should be rendered.

The following error is output to the dev console:

Uncaught TypeError: Cannot set property marked of #<Object> which has only a getter
    at index.975ef6c8.js:117651:24
    at index.975ef6c8.js:115678:72
    at index.975ef6c8.js:115682:7
    at Object.jVSjm.@parcel/transformer-js/src/esmodule-helpers.js (index.975ef6c8.js:117664:3)
    at newRequire (index.975ef6c8.js:71:24)
    at localRequire (index.975ef6c8.js:84:35)
    at Object.5JIxC../dom.js (index.975ef6c8.js:113756:17)
    at newRequire (index.975ef6c8.js:71:24)
    at localRequire (index.975ef6c8.js:84:35)
    at Object.6TtqN.../../../../base/browser/markdownRenderer.js (index.975ef6c8.js:113600:27)

### Expected Behavior

I expect to see Monaco Editor working in the web page and no errors in the dev console.

**Comment by ashleydavis** [comment]
Updating the example to the latest Parcel (2.3.2) doesn't fix the problem.


Updating to the latest monaco-editor (0.32.1) doesn't fix it either.

**Comment by ashleydavis** [comment]
Here's the stack trace for the error with source map applied:

```
Uncaught TypeError: Cannot set property marked of #<Object> which has only a getter
    at marked.js:2934:17
    at marked.js:22:66
    at marked.js:25:2
    at Object.jVSjm.@parcel/transformer-js/src/esmodule-helpers.js (marked.js:2947:2)
    at newRequire (index.975ef6c8.js:71:24)
    at localRequire (index.975ef6c8.js:84:35)
    at Object.5JIxC../dom.js (markdownRenderer.js:19:7)
    at newRequire (index.975ef6c8.js:71:24)
    at localRequire (index.975ef6c8.js:84:35)
    at Object.6TtqN.../../../../base/browser/markdownRenderer.js (markdownRenderer.js:24:7)
(anonymous) @ marked.js:2934
(anonymous) @ marked.js:22
(anonymous) @ marked.js:25
jVSjm.@parcel/transformer-js/src/esmodule-helpers.js @ marked.js:2947
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
5JIxC../dom.js @ markdownRenderer.js:19
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
6TtqN.../../../../base/browser/markdownRenderer.js @ markdownRenderer.js:24
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
9rrQP.../../../../base/browser/dom.js @ markdownHoverParticipant.js:19
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
5ohlO.../../../../base/browser/dom.js @ contentHover.js:25
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
hZr3O.../../../../base/common/keyCodes.js @ hover.js:21
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
39qli.../../../../base/common/lifecycle.js @ colorContributions.js:9
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
6odjy../browser/controller/coreCommands.js @ editor.all.js:16
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
a2trk../editor.all.js @ edcore.main.js:5
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
34CrE.../basic-languages/monaco.contribution @ editor.main.js:7
newRequire @ index.975ef6c8.js:71
localRequire @ index.975ef6c8.js:84
8lqZg.url:monaco-editor/esm/vs/language/json/json.worker.js @ index.js:6
newRequire @ index.975ef6c8.js:71
(anonymous) @ index.975ef6c8.js:122
(anonymous) @ index.975ef6c8.js:145
Show 7 more frames
```

**Comment by NO-MAP** [comment]
### same error.

i am using `monaco-editor` with  `vite`.

got this error
```
Uncaught TypeError: Cannot set property marked of #<Object> which has only a getter
    at marked.js:2934
```

the error code is
```
exports.marked = marked;
```

temporary fix:
```
// exports.marked = marked;
Object.defineProperty(exports, 'marked', marked)
```
there should be some better solutions.

this might be  related to `esbuild`.
[Cannot set property of #<Object> which has only a getter](https://github.com/evanw/esbuild/issues/587 )

**Comment by graphemecluster** [comment]
**Related:** https://github.com/parcel-bundler/parcel/issues/5011

I am using the editor with React and Parcel and encounter the same problem.

With @NO-MAP's temporary fix, the source code compiles successfully but then the error same as #3035 occurs. No workarounds suggested in the comments in #3035 works.

**Comment by graphemecluster** [comment]
**Info:** the change was introduced in https://github.com/microsoft/vscode/commit/bd369c638ea582aedb3dcd9d05eb8dcd2158496f.

**Comment by PredokMiF** [comment]
I got same issue. Version downgrade was helped me:
```
monaco-editor@0.31.1
@monaco-editor/loader@1.3.2
@monaco-editor/react@4.4.5```

**Comment by hediet** [comment]
Is someone up for a PR to fix this?

**Comment by maxburs** [comment]
@hediet Created a PR here: https://github.com/microsoft/vscode/pull/178179

**Comment by bibek-stripe** [comment]
Looks like that PR was merged, is this issue resolved in monaco-editor now?

**Comment by Mai-Lapyst** [comment]
Can comfirm that the example [browser-esm-parcel](https://github.com/microsoft/monaco-editor/tree/main/samples/browser-esm-parcel) works when upgrading to aleast `0.37.1` (only tested it with the latest parcel version of `2.9.3`). Also works in the most recent version of `0.43.0`.

**Comment by sabberworm** [comment]
FWIW, versions 0.38.0 through 0.45.0 were all working fine for me when bundling with parcel. Starting with 0.46.0, the build fails again, due to the way parcel shims the `process` global.
It seems the maintainers noticed this (see 8617a8af9e1d30366e8bea7063382b43fc62a589 and 9488e7e078b8252e0e5401759be3b025384e1119) but otherwise didn’t do anything about it.

**Comment by maxburs** [comment]
@sabberworm We worked around this by patching Monaco. You can see the patch here: https://github.com/Azure/monaco-kusto/blob/master/.yarn/patches/monaco-editor-npm-0.46.0-fb69b10c11.patch

I haven't tried opening a PR with that patch because it seems more like a Parcel issue than a Monaco one, but, the patch also seems fairly innocuous if anyone else wants to give it a shot.
