### ISSUE TITLE
[Bug] Unexpected usage when specifying language

### ISSUE THREAD

**Issue by alsoicode** [microsoft/monaco-editor#3077]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

In my Angular 13 project, using monaco-editor 0.33.0, I am loading the Monaco editor in my Angular project via this method, which adds the "loader.js" script tag to the document:

```typescript
loadMonaco(): void {
    const loader = (): void => {
      const vsPath = this.monacoPath;
      (window as any).amdRequire = (window as any).require;
      (window as any).amdRequire.config({ paths: { vs: vsPath } });

      // Load monaco
      (window as any).amdRequire(['vs/editor/editor.main'], () => {
          this.ngZone.run(() => {
            this.isMonacoLoaded$.next(true);
            console.log('loader finished');
          });
      }, (error) => console.error('Error loading monaco-editor: ', error));
    };

    // Check if AMD loader already available
    const isAmdLoaderAvailable = !!(window as any).amdRequire;

    if (isAmdLoaderAvailable) {
      return loader();
    }

    const loaderScript: HTMLScriptElement = document.createElement('script');
    loaderScript.type = 'text/javascript';
    loaderScript.src = `${ this.monacoPath }/loader.js`;
    loaderScript.id = 'monacoLoader';
    loaderScript.addEventListener('load', loader);
    document.body.appendChild(loaderScript);
  }
```

I see the following JS resources loaded in my network activity:

 - loader.js
 - editor.main.js
 - editor.main.nls.js

In my component, I am observing `isMonacoLoaded$`:

```typescript
ngOnInit(): void {
    this.editorService
        .isMonacoLoaded$
        .pipe(
          filter(isLoaded => isLoaded),
          take(1),
        )
        .subscribe((loaded) => {
          this.initMonaco();
        });
  }
```

From there, I am creating the monaco editor instance:

```typescript
initMonaco(): void {
    const options: monaco.editor.IStandaloneEditorConstructionOptions = {
      ...this.defaultOptions,
      ...this.options,
      value: this.value,
    };

    this.editorService.setCustomTheme();

    this.editor = monaco.editor.create(this.editorElement.nativeElement, options);

    const model = this.editor.getModel();

    this.value = model.getValue();
  }
```

The problem is, that if I specify a `language` in the options, I get the following errors:

```
ERROR Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:1)
    at webWorker.js:38:1
    at _ZoneDelegate.push.23484._ZoneDelegate.invoke (zone.js:409:1)
    at Object.onInvoke (core.mjs:25568:1)
    at _ZoneDelegate.push.23484._ZoneDelegate.invoke (zone.js:408:1)
    at Zone.push.23484.Zone.run (zone.js:169:1)
    at zone.js:1326:1
    at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:443:1)
    at Object.onInvokeTask (core.mjs:25555:1)
    at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:442:1)
    at errors.js:12:1
    at timer (zone.js:3128:1)
    at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:443:1)
    at Object.onInvokeTask (core.mjs:25555:1)
    at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:442:1)
    at Zone.push.23484.Zone.runTask (zone.js:214:1)
    at push.23484.ZoneTask.invokeTask (zone.js:525:1)
    at ZoneTask.invoke (zone.js:514:1)
    at data.args.<computed> (zone.js:3108:1)
```

What am I doing wrong?

**Comment by alsoicode** [comment]
I figured it out. You just have to access the right instance of the editor, which should be `window.monaco.editor`. Once you change which object you're using, everything works as expected.

The error is not helpful - at all, but I hope my post will help anyone who may come across this in the future as I had a hell of a time finding any sort of documentation regarding this. In fact, I didn't find any documentation at all. I just happened to try this from looking at other people's code samples.
