### ISSUE TITLE
"Could not find file ..." error on editor dispose.

### ISSUE THREAD

**Issue by Smesharikable** [Microsoft/monaco-editor#335]
monaco-editor npm version: 0.8.0

I have the following error when I quickly create and dispose editor with some typescript code.

`Error: Could not find file: 'inmemory://model/default'. 
at i (http://localhost:8889/node_modules/monaco-editor/dev/vs/language/typescript/lib/typescriptServices.js:58:30724) 
at Object.l [as getSyntacticDiagnostics] (http://localhost:8889/node_modules/monaco-editor/dev/vs/language/typescript/lib/typescriptServices.js:59:1460) 
at e.getSyntacticDiagnostics (http://localhost:8889/node_modules/monaco-editor/dev/vs/language/typescript/src/worker.js:9:1738) 
at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.fmr (http://localhost:8889/node_modules/monaco-editor/dev/vs/base/worker/workerMain.js:10654:77) 
at SimpleWorkerServer._handleMessage (http://localhost:8889/node_modules/monaco-editor/dev/vs/base/worker/workerMain.js:8313:78) 
at Object.handleMessage (http://localhost:8889/node_modules/monaco-editor/dev/vs/base/worker/workerMain.js:8299:71) 
at SimpleWorkerProtocol._handleMessage (http://localhost:8889/node_modules/monaco-editor/dev/vs/base/worker/workerMain.js:8170:40) 
at SimpleWorkerProtocol.handleMessage (http://localhost:8889/node_modules/monaco-editor/dev/vs/base/worker/workerMain.js:8142:18) 
at SimpleWorkerServer.onmessage (http://localhost:8889/node_modules/monaco-editor/dev/vs/base/worker/workerMain.js:8303:28) 
at self.onmessage (http://localhost:8889/node_modules/monaco-editor/dev/vs/base/worker/workerMain.js:10743:71)
message:
"Could not find file: 'inmemory://model/default'."`

There is a demo page code for error reproducing: [monaco-editor error demo](https://gist.github.com/Smesharikable/d90e53dbe6a2b6dfde972de42500e01b). Click "Create" and then "Close" within a second.

This exception is occurs when **noSemanticValidation** or **noSyntaxValidation** is **false**.

It seems like a DiagnostcsAdapter is trying to access disposed model. May be the reason is that a TypeScript worker is keep working after editor and model have been disposed.

**So what is a proper way to dispose the editor?**

Also I would like to draw attention to the [suspicious method](https://github.com/Microsoft/monaco-typescript/blob/master/src/mode.ts#L56) that can be reason of this error. We collect all disposables but will never use it as I understand.

Thanks in advance!

**Comment by Smesharikable** [comment]
Ok, it seems like checking model listeners before requesting diagnostics resolves my issue.  

Modified method from DiagnosticsAdapter:

	private _doValidate(resource: Uri): void {
		let workerPromise = this._worker(resource);
		let diagnosticsPromise = workerPromise.then(worker => {
			const promises: Promise<ts.Diagnostic[]>[] = [];
			const {noSyntaxValidation, noSemanticValidation} = this._defaults.getDiagnosticsOptions();
			if (!noSyntaxValidation && this._listener[resource.toString()]) {
				promises.push(worker.getSyntacticDiagnostics(resource.toString()));
			}
			if (!noSemanticValidation && this._listener[resource.toString()]) {
				promises.push(worker.getSemanticDiagnostics(resource.toString()));
			}
			return Promise.join(promises);
		});
		let setMarkerPromise = diagnosticsPromise.then(diagnostics => {
			if (!this._listener[resource.toString()]) {
				return Promise.wrap(undefined);
			}
			const markers = diagnostics
                .reduce((p, c) => c.concat(p), [])
                .map(d => this._convertDiagnostics(resource, d));

			monaco.editor.setModelMarkers(monaco.editor.getModel(resource), this._selector, markers);
		});
		setMarkerPromise.done(undefined, err => {
			console.error(err);
		});
	}
