### ISSUE TITLE
[Bug] Setting typescript `strictNullChecks` compiler option throws error

### ISSUE THREAD

**Issue by shaharkazaz** [microsoft/monaco-editor#3478]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({strictNullChecks: true});
monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'typescript'
});
```

### Reproduction Steps

1. Run the code snippet above.
2. Move the cursor in the editor.

### Actual (Problematic) Behavior

The following error is thrown:
```
errors.ts:26 
        
       Uncaught Error: Could not find source file: 'inmemory://model/1'.

Error: Could not find source file: 'inmemory://model/1'.
    at Ve (tsWorker.js:255:8493)
    at Object.An [as getQuickInfoAtPosition] (tsWorker.js:255:14559)
    at lm.getQuickInfoAtPosition (tsWorker.js:33955:3428)
    at S.fmr (workerMain.js:22:33695)
    at f._handleMessage (workerMain.js:22:17684)
    at Object.handleMessage (workerMain.js:22:17309)
    at w._handleRequestMessage (workerMain.js:22:14120)
    at w._handleMessage (workerMain.js:22:13570)
    at w.handleMessage (workerMain.js:22:13458)
    at f.onmessage (workerMain.js:22:17401)
    at errors.ts:26:12
```

### Expected Behavior

No error should be thrown.

**Comment by shaharkazaz** [comment]
Resolved by merging with the current options:
```
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
...monaco.languages.typescript.typescriptDefaults.getCompilerOptions(),
  strictNullChecks: true
});
```
