### ISSUE TITLE
suggestion throws an error when triggered on specific text[Bug] 

### ISSUE THREAD

**Issue by jkalq** [microsoft/monaco-editor#3526]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
case
```

### Reproduction Steps

input text "case"
trigger suggestion

### Actual (Problematic) Behavior
error is thrown in console:

errors.ts:26 Uncaught Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'Mo'.

Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'Mo'.
    at Object.Rn [as cast] (tsWorker.js:9:21239)
    at Be (tsWorker.js:247:49873)
    at _e (tsWorker.js:247:54111)
    at Object.L [as getCompletionsAtPosition] (tsWorker.js:247:30870)
    at Object.a [as getCompletionsAtPosition] (tsWorker.js:255:14077)
    at lm.getCompletionsAtPosition (tsWorker.js:33955:3086)
    at S.fmr (workerMain.js:22:33695)
    at f._handleMessage (workerMain.js:22:17684)
    at Object.handleMessage (workerMain.js:22:17309)
    at w._handleRequestMessage (workerMain.js:22:14120)
    at errors.ts:26:12

### Expected Behavior

No uncaught error in console

**Comment by hediet** [comment]
I think this is a bug in typescript, not in monaco.

**Comment by jkalq** [comment]
Should I create a counterpart issue in the Typescript repo ?

**Comment by hediet** [comment]
Maybe this is because we use an older version of TypeScript.
