### ISSUE TITLE
[Bug] Uncaught Error: Illegal value for lineNumber

### ISSUE THREAD

**Issue by BeishaoCao-db** [microsoft/monaco-editor#3572]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

N/A

### Monaco Editor Playground Code

```typescript
N/A
```

### Actual (Problematic) Behavior

Uncaught Error: Illegal value for lineNumber
at None (webpack://node_modules/monaco-editor/esm/vs/editor/common/model/textModel.js:547:18)
at getLineMaxColumn (webpack://node_modules/monaco-editor/esm/vs/editor/contrib/hover/browser/markdownHoverParticipant.js:59:32)
at computeSync (webpack://node_modules/monaco-editor/esm/vs/editor/contrib/hover/browser/contentHover.js:492:47)
at computeSync (webpack://node_modules/monaco-editor/esm/vs/editor/contrib/hover/browser/hoverOperation.js:122:62)
at _triggerSyncComputation (webpack://node_modules/monaco-editor/esm/vs/editor/contrib/hover/browser/hoverOperation.js:49:83)
at call (webpack://node_modules/monaco-editor/esm/vs/base/common/async.js:404:67)
at doRun (webpack://node_modules/monaco-editor/esm/vs/base/common/async.js:399:17)

And
Error: Illegal value for lineNumber
at None (webpack://node_modules/monaco-editor/esm/vs/editor/browser/view/viewLayer.js:43:18)
at getLine (webpack://node_modules/monaco-editor/esm/vs/editor/browser/view/viewLayer.js:249:37)
at getVisibleLine (webpack://node_modules/monaco-editor/esm/vs/editor/browser/viewParts/lines/viewLines.js:389:51)
at _updateLineWidths (webpack://node_modules/monaco-editor/esm/vs/editor/browser/viewParts/lines/viewLines.js:381:13)

### Expected Behavior

Not having these error

### Additional Context

Similar stuff happens in vscode recently:
https://github.com/microsoft/vscode/issues/172791

**Comment by hediet** [comment]
Please provide reproduction steps and properly fill out the issue form. Just the stack trace doesn't help much. Thanks!
