### ISSUE TITLE
"Unexpected usage at EditorSimpleWorker.loadForeignModule" after upgrading monaco-editor

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#3856]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I have a ReactJS project using monaco-editor and react-monaco-editor. Previously, the project could be compiled with this [yarn.lock](https://gist.github.com/chengtie/05c1018a7d1ac2e88813d531268dbd1e), and the editor worked fine. But we realized that our `package.json` could not generate that yarn.lock anymore and we had to upgrade typescript to be able to compile with a newly generated yarn.lock. Then, we had to upgrade monacpo-editor and react-monaco-editor, otherwise hovering on the editor did not trigger anything anymore. Finally, we used the following `package.json` which generated this new [yarn.lock](https://gist.github.com/chengtie/d3d5b2280dc16afe43fa8eed39a6175b).

```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@codingame/monaco-languageclient": "^0.17.3",
    "@fluentui/react": "^8.33.0",
    "@fluentui/react-components": "^9.7.2",
    "@handsontable/react": "^9.0.2",
    "@material-ui/core": "^4.9.8",
    "@microsoft/office-js-helpers": "^1.0.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/react-stripe-elements": "^6.0.4",
    "@uifabric/react-cards": "^0.109.49",
    "allotment": "^1.17.1",
    "axios": "^0.19.2",
    "color": "^3.1.2",
    "copy-to-clipboard": "^3.3.1",
    "cross-storage": "^1.0.0",
    "dva": "^2.4.1",
    "dva-model-creator": "^0.4.3",
    "formik": "^2.1.4",
    "handsontable": "^9.0.2",
    "highcharts": "^7.0.3",
    "highcharts-react-official": "^3.0.0",
    "i18next": "^22.4.10",
    "is-primitive": "^3.0.1",
    "lodash": "^4.17.15",
    "markdown-to-jsx": "^7.1.9",
    "moment": "^2.24.0",
    "monaco-editor": "^0.36.1",
    "node-sass": "^4.14.1",
    "office-ui-fabric-core": "^11.0.0",
    "office-ui-fabric-react": "^7.105.4",
    "query-string": "^6.11.1",
    "react": "^16.13.1",
    "react-app-polyfill": "^1.0.6",
    "react-bootstrap": "^1.0.1",
    "react-dom": "^16.13.1",
    "react-i18next": "^12.2.0",
    "react-intl": "^6.2.10",
    "react-markdown": "^8.0.5",
    "react-meta-tags": "^1.0.1",
    "react-monaco-editor": "^0.52.0",
    "react-scripts": "3.4.1",
    "react-stripe-elements": "^6.1.1",
    "react-syntax-highlighter": "^15.5.0",
    "redux-devtools-extension": "^2.13.8",
    "rehype-raw": "^6.1.1",
    "remark-gfm": "^3.0.1",
    "remark-parse": "^10.0.1",
    "styled-components": "^5.3.5",
    "unified": "^10.1.2",
    "yup": "^0.28.3"
  },
  "scripts": {
    "start": "PORT=3000 react-app-rewired start",
    "start:https": "HTTPS=true  react-app-rewired start",
    "build": "GENERATE_SOURCEMAP=false react-scripts --max_old_space_size=8096 build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ],
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/preset-env": "^7.20.2",
    "@types/color": "^3.0.1",
    "@types/cross-storage": "^0.8.29",
    "@types/jest": "^25.1.4",
    "@types/lodash": "^4.14.149",
    "@types/node": "^13.9.5",
    "@types/office-js": "^1.0.92",
    "@types/query-string": "^6.3.0",
    "@types/react": "^16.9.27",
    "@types/react-dom": "^16.9.5",
    "@types/react-redux": "^7.1.7",
    "@types/styled-components": "^5.0.1",
    "@types/yup": "^0.26.33",
    "css-loader": "^3.5.3",
    "react-app-rewired": "^2.1.8",
    "style-loader": "^1.2.1",
    "typescript": "^5.0.2"
  },
  "resolutions": {
    "@types/react": "17.0.2",
    "@types/react-dom": "17.0.2",
    "@babel/preset-env": "7.20.2"
  }
}
```

`webpack.config.js`:

```
const WEBPACK = require('webpack');
const PATH = require('path');

module.exports = {
    resolve: {
        extensions: ['.js', '.jsx']
    },
    context: __dirname,
    entry: {
        app: ['./src/index.jsx'] // app: ['./MY_FOLDER_INPUT/MY_FILE_INDEX.jsx']
    },
    output = {
        path: PATH.join(__dirname, '/MY_FOLDER_OUTPUT'),
        filename: 'index.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader"
                }
            }
        ]
    }
};
```

`config-overrides.js`:

```
module.exports = function override (config, env) {
    console.log("inside config-overrides.js")

    // config.resolve.alias['vscode'] = require.resolve('@codingame/monaco-languageclient/lib/vscode-compatibility')
    
    // disable chunks so the index.html won't change during development 
    config.optimization.splitChunks = {
        cacheGroups: {
            default: false,
        },
    };

    config.optimization.runtimeChunk = false;

    return config;
}
```

Now, `sudo PORT=8000 HTTPS=true SSL_CRT_FILE=ssl/cert.pem SSL_KEY_FILE=ssl/key.pem ./node_modules/.bin/react-scripts start` can compile the project. 
However, hovering on a text in the editor triggers:

```
Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:469:1)
    at webWorker.js:38:1
    at errors.js:15:1
```

[![enter image description here][1]][1]

Does anyone know how to solve this?

(SO: https://stackoverflow.com/questions/75806209/unexpected-usage-at-editorsimpleworker-loadforeignmodule)

  [1]: https://i.stack.imgur.com/yMtD3.png

**Comment by chengtie** [comment]
> What language are you using? It looks like you might be using JavaScript or TypeScript. If so, you need to make sure your Chrome browser version is higher than 80.

I'm using TypeScript, and Chrome `Version 111.0.5563.64 (Official Build) (x86_64)`

**Comment by tamayika** [comment]
monaco-languageclient does not support monaco-editor 0.36.x until [PR](https://github.com/TypeFox/monaco-languageclient/pull/470) is merged.
See [compatibility table](https://github.com/TypeFox/monaco-languageclient#monaco-editor-compatibility-table).

**Comment by chengtie** [comment]
> monaco-languageclient does not support monaco-editor 0.36.x until [PR](https://github.com/TypeFox/monaco-languageclient/pull/470) is merged. See [compatibility table](https://github.com/TypeFox/monaco-languageclient#monaco-editor-compatibility-table).

Thank you. When you say "monaco-languageclient", are you referring to `"@codingame/monaco-languageclient": "^0.17.3",` I'm using?

**Comment by tamayika** [comment]
Yes `@codingame/monaco-languageclient` was renamed to `monaco-languageclient`.
`@codingame/monaco-languageclient` was published a year ago.

**Comment by chengtie** [comment]
> Yes `@codingame/monaco-languageclient` was renamed to `monaco-languageclient`. `@codingame/monaco-languageclient` was published a year ago.

So may I leave `"@codingame/monaco-languageclient": "^0.17.3"` in `package.json` as it is?

I tried to add  `"resolutions": { "monaco-editor": "0.31.1" }`, the problem was solved.

**Comment by chengtie** [comment]
> If you are not using monaco-languageclient (or don't know what it is), please remove it. And monaco-editor-webpack-plugin can integrate monaco-editor and webpack easily. Please see [example](https://github.com/microsoft/monaco-editor/tree/main/samples/browser-esm-webpack-monaco-plugin). react-monaco-editor also provides the similar [example](https://github.com/react-monaco-editor/react-monaco-editor#using-with-webpack).

@codingame/monaco-languageclient is indeed used in our code such as `import { MonacoToProtocolConverter, ProtocolToMonacoConverter } from '@codingame/monaco-languageclient/lib/monaco-converter'` and `import { integer } from "@codingame/monaco-languageclient";`.

This issue can be considered solved.

Thank you very much.

**Comment by RyanHo97** [comment]
Hello, I have encountered a similar issue, but I am using vite+vue2. This is an error screenshot. May I ask how to solve this problem：
![image](https://github.com/microsoft/monaco-editor/assets/49436413/13ea0d5e-fa16-46a3-9a83-f312a87c6d89)

package.json:
`{
  "name": "rfly-create-vite4-vue2+elementui",
  "version": "0.0.1",
  "scripts": {
    "serve": "vite",
    "serve:dev": "vite --mode development",
    "serve:prod": "vite --mode production",
    "build": "vite build",
    "build:dev": "vite build --mode development",
    "build:prod": "vite build --mode production"
  },
  "dependencies": {
    "axios": "^1.4.0",
    "element-ui": "^2.15.13",
    "vite": "^4.3.5",
    "vue": "^2.7.14",
    "vue-router": "^3.5.3",
    "vuex": "^3.6.2",
    "monaco-editor": "^0.38.0"
  },
  "devDependencies": {
    "@babel/core": "^7.21.8",
    "@babel/preset-env": "^7.21.5",
    "@vitejs/plugin-legacy": "^4.0.3",
    "babel-plugin-component": "^1.1.1",
    "rollup": "^3.21.6",
    "rollup-plugin-commonjs": "^10.1.0",
    "sass": "^1.49.0",
    "terser": "^5.17.3",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-vue2": "^2.0.3",
    "vue-template-compiler": "^2.6.14"
  },
  "resolutions": {
    "monaco-editor": "^0.38.0"
  }
}
`
