### ISSUE TITLE
[Bug] RangeError:Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lansefengxinzi** [microsoft/monaco-editor#3927]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.languages.registerCompletionItemProvider(this.languageId, {
            triggerCharacters: this.triggerCharacters,
            provideCompletionItems: (document, position, token, context) => {
                const privoder = this.completionMap.get(document.uri.toString());
                if (!privoder) {
                    return { suggestions: [] };
                }
                return privoder.provideCompletionItems(document, position, token, context);
            }
        });
```

### Actual (Problematic) Behavior

node_modules/monaco-editor/esm/vs/platform/contextkey/common/scanner.js: Maximum call stack size exceeded
    at NodePath.setContext (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/context.js:118:20)
    at /Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/family.js:252:10
    at Array.map (<anonymous>)
    at NodePath._getKey (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/family.js:245:22)
    at NodePath.get (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/family.js:236:17)
    at maybeReplaceWithRegExpLiteral (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/babel-plugin-transform-regexp-constructors@0.4.3/node_modules/babel-plugin-transform-regexp-constructors/lib/index.js:29:50)
    at PluginPass.NewExpression (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/babel-plugin-transform-regexp-constructors@0.4.3/node_modules/babel-plugin-transform-regexp-constructors/lib/index.js:43:9)
    at newFn (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/visitors.js:149:21)
    at NodePath._call (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/context.js:80:31)
    at TraversalContext.visitQueue (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitQueue (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/Users/sunfei/Documents/phoenix/frontend/common/temp/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/context.js:91:21)

### Additional Context

use 0.36.0 ,it,s ok. upgrade 0.37.1. get this error message

typescript 4.8.2

**Comment by hediet** [comment]
Please provide an example that reproduces in the monaco editor. Thanks for understanding!
