### ISSUE TITLE
[Bug] Linked editing causing uncaught exception

### ISSUE THREAD

**Issue by yanny7** [microsoft/monaco-editor#4312]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0#XQAAAAIwAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0o4-InmJTiNdlbZ8DX-17E4KVEqPLe3831nfbDw-lE-iUSXBko7Q2YS-nwSVoWCNGfTlXFLMDHAHT_6RfhcKPRcYAb0RauRToPmyD6UJS1cbwD81dipZCUOzf6GVWX2bEn_OR6P6SOv_6Ks1vagzJkfFv04Y6CGgZr1CfHEalURxCVojnKh3esUzYyS_Ak8GkkXayQPZYrizVNilLD4mDYK9RHTgAg1mnN6Ld4l2-V38h4xlwf8noJtAEqiYPBT6CUVp5UqDd5DJfiQu-WVW4yLlVpElO3gNGuF8X1TbU-spCOOTkH1PbIfCBfj3zGB1rt6PAIcOOeT88ADK-ZVH4XB7alJBkve5kQeC-9x4N2gD2yAfr1YqZvPbSIe2X__NJMSj

### Monaco Editor Playground Code

```typescript
monaco.languages.register({ id: "mySpecialLanguage" });


monaco.languages.registerLinkedEditingRangeProvider("mySpecialLanguage", {
	provideLinkedEditingRanges: function(model, position) {
		return new Promise((resolve) => {
			console.log(position);
			setTimeout(() => {
				resolve( {
					ranges: []
				})
			}, 500)
		})
	}
});

monaco.editor.create(document.getElementById("container"), {
	value: "\n\nHover over this text",
	language: "mySpecialLanguage",
	linkedEditing: true,
});
```

### Reproduction Steps

1. Write some random text to edit area
2. Observe console

### Actual (Problematic) Behavior

Console is spammed by Uncaught exception (in Promise)

### Expected Behavior

No exception caused by linked editing

### Additional Context

Issue is visible only when delayed response to provideLinkedEditingRanges

**Comment by aeschli** [comment]
I see the Cancel exception. Is that the one you are referring to?
```
async.ts:29 
        
       Uncaught (in promise) Canceled: Canceled
    at UniqueContainer.value (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:50448:24)
    at Emitter._deliver (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12612:26)
    at Emitter.fire (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12642:22)
    at MutableToken.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:13137:35)
    at CancellationTokenSource.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:13184:29)
    at Object.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:50462:24)
    at LinkedEditingContribution.clearRanges (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:154584:38)
    at LinkedEditingContribution.updateRanges (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:154614:18)
    at _rangeUpdateTriggerPromise.rangeUpdateScheduler.trigger._a (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:154481:91)
    at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:50631:32
```

**Comment by yanny7** [comment]
Yes, it is the same (from playground page):

```
Uncaught (in promise) Canceled: Canceled
    at UniqueContainer.value (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:50448:24)
    at Emitter._deliver (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12612:26)
    at Emitter.fire (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12642:22)
    at MutableToken.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:13137:35)
    at CancellationTokenSource.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:13184:29)
    at Object.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:50462:24)
    at LinkedEditingContribution.clearRanges (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:154584:38)
    at LinkedEditingContribution.updateRanges (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:154614:18)
    at _rangeUpdateTriggerPromise.rangeUpdateScheduler.trigger._a (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:154481:91)
    at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:50631:32
```
