### ISSUE TITLE
[Bug] 0.47.0 TypeError: Cannot read properties of undefined (reading 'CI')

### ISSUE THREAD

**Issue by YeKelvin** [microsoft/monaco-editor#4417]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

vue3 vite

### Actual (Problematic) Behavior

TypeError: Cannot read properties of undefined (reading 'CI')
    at node_modules/.pnpm/monaco-editor@0.47.0/node_modules/monaco-editor/esm/vs/base/common/platform.js (platform.js:42:27)
    at __init (chunk-GFT2G5UO.js?v=536ba6aa:15:56)
    at node_modules/.pnpm/monaco-editor@0.47.0/node_modules/monaco-editor/esm/vs/base/common/async.js (async.js:9:1)
    at __init (chunk-GFT2G5UO.js?v=536ba6aa:15:56)
    at node_modules/.pnpm/monaco-editor@0.47.0/node_modules/monaco-editor/esm/vs/platform/theme/common/colorRegistry.js (colorRegistry.js:6:1)
    at __init (chunk-GFT2G5UO.js?v=536ba6aa:15:56)
    at symbolIcons.js:7:1

### Expected Behavior

Can compile normally

**Comment by sonswift** [comment]
I faced to the same issue at https://github.com/microsoft/monaco-editor/issues/4402 but nothing update in version 0.47.0. 
It started from https://github.com/microsoft/vscode/pull/200935

Currently, I still keep using version 0.45.0 instead. So bad
