### ISSUE TITLE
[Feature Request] Support for package.json conditional exports map, for extra libs typings acquisition

### ISSUE THREAD

**Issue by JulianCataldo** [microsoft/monaco-editor#4464]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Actually, the only way for the TypeScript worker to pick up added libraries via `setExtraLibs` or `addExtraLib` is by using the `main` or `typings` fields inside the package.json file, or without a package.json, by using `my-lib/some-file.js` or `my-lib/dist/some-file.js`.

It works perfectly with the legacy method, but not with the newer `exports` field, which is very useful for achieving this kind of layouts:

```ts
exports: {
	'.': {
		typings: './dist/index.d.ts',
		import: './dist/index.js',
	},
	'./foo': {
		typings: './dist/foo.d.ts',
		import: './dist/foo.js',
	},
},
```

Then we can import like this: `import 'my-lib/foo';`.
This is also better than using barrel files, which are becoming an anti-pattern, because of the side-effects risks, for bundlers, browsers, CDNs…
I'm not 100% sure but all ATA (automatic types acquisition) mechanisms I tried are randomly breaking on some packages, maybe because of this limitation.

Actually with Monaco, it's not possible to consume a library subparts if it's under a dist., without resorting to single entry point with a barrel, or full, sound paths.

This is problematic because since Node 12, a lot of NPM packages are adopting the new practice while abandoning the older one, for legitimate reasons.

### Monaco Editor Playground Link

- [Link to repro. in the playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.47.0#XQAAAAL9CAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxFEkZueHknAbPiqvge2vI5ZKrRMMjk_Ak8UVPWVKF6le90RSdezmXSkBbU6S2VLhtUmWVRW0QhtvsvfgKxkWd0AZ1s3mZBIJYE8tsaTsgTHywJX4CCa23ZsKbXCY1ZXH_LXoqLhVziCZp4j_uYb5gXsKh7AikGc7EGieI5XU5Hjbrmh0-566xdDxZk0XcgyeIMKwYscEzKcDTA7xIydl4yUipym2UQvyAs8VeTGh4dLi5RzvP9DHr0FN2nHjwdKu8cJ7B9mcRhVRG6VsrSBBXSR8p1NNq02IH1-cbzZSs6xGJCH-nuGShpxkzAJ3aXm44E9qTK6ZNrvkwatp5VjBdFkGVFXuRmeg8C_Q0ktUPCt7UiEddUhHI7R431K5Owmui7LKLEhMxWfvHlJOGQKnVyW4StJyrOo4lnp2rULWwTp5oOqyWkVnJbdmsMIgTkyqn_zUyhhOW9gz_5jQTsHHD5RKu4-vnTOOSC5Wzd9XLzKt6Ash_e_EBEaWW8tC--lPKoGMP6zQwffMQe_4VS0WtasCzsXzfBH_WAH21FSzMu_Ft65FoqBnzej5xIsyJM1GMyD2xHvpvpLi6bqfvx01bpNQoycUsCw73IOESpqsda5esZfTzD6jXdLiLOn8TZZ0M1itSAu_00-d_wYF613jpRelnET8V484PS2kugJdbVFC7jEaokybYSkcB9GY5tmzPEoD81Zw9lVMdZdQLxfC4eBl0w1fbYWDjYOkjZD_Ip2CrivLaDDooqivuKuJLL2IhIwd5CNLuL_d9lc6nfcY74vUAx2aCRdfhoek2ivtYLdS_rA2DRfKdl_u4_DCcdkmscMkb8fXAam-DNo290RVOvuJDzuEKKwCmh7W9wdzSsqxSrXVBCrpEnlp93UwnqVZmN8sDi_tz2Nc7qxNm3JZmKsQrYx4RMRsaMMh8rvP4TBDGk9qiipW1iJcXwUe5Glscc1qrGVgpFpmrcbgPartmcA3IzvNMTGFlDUHHCQl2_8EMYt35Gf7OQmg-ujJa2IiYOl8FqVwFPg4qL06ZbnTh6q3oX041ZPH5yZcjKHVBhyQKY3PLlIsPhYbAo2UIQNlidctgxfqxcaQZn8D8PIh1PDk66Ipxm2LVzZgdf44ntd-BNNHf6H8xi-lhzsSuXlGOVS1QDJCI0EBKOx5yowJDOMuJ_9G4Ve0)

### Monaco Editor Playground Code

```typescript
const libs = [
  // koala
  {
    content: `
    export declare const foo: "Hey";
      `,
    filePath: "/node_modules/@types/koala/lib.d.ts",
  },
  {
    content: `
    export const foo = "Hey";
      `,
    filePath: "/node_modules/@types/koala/lib.js",
  },
  {
    content: JSON.stringify({
      name: "koala",
      version: "1.0.0",
      // typings: "./lib.d.ts",
      // main: "./lib.js",

      // v--- NOT WORKING ---v
      exports: {
        ".": "./lib.js",
      },
      type: "module",
    }),
    filePath: "/node_modules/@types/koala/package.json",
  },

  // tiger
  {
    content: `
    export declare const bar: "Hey";
      `,
    filePath: "/node_modules/@types/tiger/lib.d.ts",
  },
  {
    content: JSON.stringify({
      name: "tiger",
      version: "1.0.0",
      main: "./lib.js",
      type: "module",
    }),
    filePath: "/node_modules/@types/tiger/package.json",
  },

  // rhino
  {
    content: `
    	declare module 'rhino' {
  					export class Foo {
  						/**
  						 * # Construct me!
  						 */
  						 constructor(readonly hello: string) { } } }
    `,
    filePath: "/ambient.d.ts",
  },
];

libs.forEach((file /* libs */) => {
  console.log(file);
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    file.content,
    "file://" + file.filePath
  );
});
```

**Comment by JulianCataldo** [comment]
As a side note, maybe the lack of `"moduleResolution": "Bundler"` (or `"module": "Preserve"`) is the root cause of this.

For now, we only have those:

```ts
    export enum ModuleResolutionKind {
        Classic = 1,
        NodeJs = 2
    }
```

Also I'm not sure about how deep Monaco treats special files like tsconfig.json, package.json in the root project or dependencies, etc.

**Comment by JulianCataldo** [comment]
I may open up another issue for a bug I can minimally repro locally, but needs to be translated to the online monaco  playground.

The gist is:
- When you have some node_modules js/d.ts and their respective package.json, added as extra libs
- They use `exports`
- You import something in the model (my-package/stuff)
- What you import has a mismatch between the "real", physical path and the mapped path (my-package/stuff.js is absent from monaco POV, the mapped path is my-package/nested/stuff.js for TS)
- Monaco hands off the module resolution to the TS worker because it cannot handles it in the main thread itself.
- The TS worker returns an unclonable package.json representation

Some of those step are speculative, notably on how Monaco resolves package. I can definitely note that Monaco doesn't handles export condition (that's expected) and is relaxed with .js or not (even if forcefully stripped in the pjson `exports`). 

One thing is sure: The TS worker underneath does honor the exports condition for transient (buried) deps. just fine. It's direct import in main thread model views that cause the faulty postMessage roundtrip:

```

editor.worker.js:15 Uncaught (in promise) DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': () => ({ moduleReference, mode, packageName: packageName === moduleReference ? void 0 : packageName }) could not be cloned.
    at editor.worker.js:15:20
    at Object.sendMessage (simpleWorker.js:347:17)
    at SimpleWorkerProtocol._send (simpleWorker.js:229:23)
    at simpleWorker.js:184:18
(anonymous)	@	editor.worker.js:15
sendMessage	@	simpleWorker.js:347
_send	@	simpleWorker.js:229
(anonymous)	@	simpleWorker.js:184
Promise.then		
_handleRequestMessage	@	simpleWorker.js:183
_handleMessage	@	simpleWorker.js:151
handleMessage	@	simpleWorker.js:120
onmessage	@	simpleWorker.js:354
globalThis.onmessage	@	editor.worker.js:18

```
