### ISSUE TITLE
[Bug] Error: AbstractContextKeyService has been disposed

### ISSUE THREAD

**Issue by SheaJanke** [microsoft/monaco-editor#4581]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual (Problematic) Behavior

I'm getting the following console error when closing a modal containing a DiffEditor:

```
Error: AbstractContextKeyService has been disposed
    at ScopedContextKeyService.contextMatchesRules (contextKeyService.js:241:19)
    at MenuInfo_1.createActionGroups (menuService.js:222:45)
    at MenuImpl.getActions (menuService.js:362:31)
    at FromEventObservable._getValue (gutterFeature.js:47:86)
    at FromEventObservable.handleEvent [as value] (utils.js:49:35)
    at DebounceEmitter._deliver (event.js:916:22)
    at DebounceEmitter.fire (event.js:946:18)
    at DebounceEmitter.resume (event.js:1001:27)
    at event.js:1035:22
    at errors.js:15:27
 ```

Editor Options: 
```
{
  automaticLayout: true,
  find: {
    addExtraSpaceOnTop: false,
  },
  glyphMargin: true,
  readOnly: true,
  scrollbar: {
    alwaysConsumeMouseWheel: false,
  },
  scrollBeyondLastLine: false,
  quickSuggestions: true,
}
```

### Expected Behavior

No console error.

### Additional Context

This error only occurs when `renderGutterMenu: true` (which is the default). The error is not present in versions <= 0.47.0.

**Comment by kaiyoma** [comment]
vscode has been seeing this issue for a couple months now: https://github.com/microsoft/vscode/issues/210947

**Comment by kareldonk** [comment]
Yes also getting this in version 0.50.0.
Example stack trace in browser log:

```
Uncaught Error: AbstractContextKeyService has been disposed

Error: AbstractContextKeyService has been disposed
    at v.contextMatchesRules (contextKeyService.ts:287:10)
    at t.createActionGroups (menuService.ts:242:33)
    at l.getActions (menuService.ts:411:25)
    at o._getValue (gutterFeature.ts:40:91)
    at g.handleEvent [as value] (utils.ts:80:25)
    at p._deliver (event.ts:1179:13)
    at p.fire (event.ts:1210:9)
    at p.resume (event.ts:1289:12)
    at event.ts:1328:10
    at v.contextMatchesRules (contextKeyService.ts:287:10)
    at t.createActionGroups (menuService.ts:242:33)
    at l.getActions (menuService.ts:411:25)
    at o._getValue (gutterFeature.ts:40:91)
    at g.handleEvent [as value] (utils.ts:80:25)
    at p._deliver (event.ts:1179:13)
    at p.fire (event.ts:1210:9)
    at p.resume (event.ts:1289:12)
    at event.ts:1328:10
    at errors.ts:26:12
```

Seems to happen when an editor is disposed and created again very quickly in my case but not sure. Have not had time yet to debug.

**Comment by huarse** [comment]
Why is this bug still there after all this time? I've tried all sorts of methods but can't get rid of it.

```
editor.api-CalNCsUg.js:3 Uncaught Error: AbstractContextKeyService has been disposed

Error: AbstractContextKeyService has been disposed
    at JOe.contextMatchesRules (https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:888:20181)
    at yw.createActionGroups (https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:390:10358)
    at xk.getActions (https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:390:12879)
    at Mc._getValue (https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:390:23902)
    at Mc.handleEvent [as value] (https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:8:16359)
    at p6._deliver (https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:7:2719)
    at p6.fire (https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:7:3039)
    at p6.resume (https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:7:3712)
    at https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/editor.api-CalNCsUg.js:7:4067
```

**Comment by kareldonk** [comment]
Microslop doesn't seem to care anymore.
