### ISSUE TITLE
[Bug] globalDefine is not a function

### ISSUE THREAD

**Issue by create3000** [microsoft/monaco-editor#4694]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

As of version 0.51.0 I get this error, and therefor cannot update.

I only get this error when I use Monaco in an Electron environment and with Node `require`. The web version works fine.

### Actual (Problematic) Behavior

```
Uncaught TypeError: globalDefine is not a function
    at Object.<anonymous> (editor.main.js:5:395)
    at r._createAndEvalScript (/Users/holger/Desktop/X_ITE/sunrize/node_modules/monaco-editor/min/vs/loader.js:7:2506)
    at /Users/holger/Desktop/X_ITE/sunrize/node_modules/monaco-editor/min/vs/loader.js:7:2147
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```

**Comment by a10036gt** [comment]
Me too.

**Comment by nuclearsecrecy** [comment]
Same issue. Had to roll back to 0.50.0 to make it work at all in Node/Electron.

**Comment by LlanosLautaro** [comment]
same error

**Comment by 00jeser** [comment]
same
