### ISSUE TITLE
[Bug] Uncaught context cancellation error when using an inline provider

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/monaco-editor#4767]
### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.0#XQAAAAIHAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0ZaM6AEiAKctgAboa7AI8gn8BvNILczn-ntn_Op7J0iRiSJoSu8H-xEmbUTTxoDxiCFJnJB__-tl61bXWsYajlaxKSnlOpvUCnmPrnnXffnwnYRri2goI2pZOIVa4-lvv96se_l5fCIXld3qjIeDIH6yOKHZQUXq_vxTRha6CVReTK0AhPMNml7WO9U2AXhR63ewx2muJQD4NWSmjDnhnp5otSyhXXruKxFjIj-nIqQTLo6Jmckx1aYBBXQoJkxppW2fxcG7vo9zmziyDTTg9VjtbE9forAZvjbWo8JWTDL9TcLgdf1R3aQEEkgCfRdjTq6UaNauBbXSOtO3kphjmgXj23Fbkzw0l665avcf_5kNwAA

### Monaco Editor Playground Code

```typescript
const value = "";
const editor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "plaintext",
});

monaco.languages.registerInlineCompletionsProvider("plaintext", {
	provideInlineCompletions(model, position, context, token) {
		return {
			items: [
				{
					insertText: "abc"
				},
				{
					insertText: {
						snippet: "var variable = \"${1:value}\""
					}
				}
			]
		};
	},

	freeInlineCompletions() {

	}
});
```

### Reproduction Steps

**Browser:** Google Chrome Version 131.0.6778.85 (Official Build) (arm64)
**Operating System:** macOS Sonoma 14.4
 
1. Type `v` in the preview editor.
2. The inline completion should appear.
3. Hit the <kbd>Tab</kbd> key.
4. An error will now appear in the browser console.
```
editor.main.js:52017 Uncaught (in promise) Canceled: Canceled
    at UniqueContainer.value (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:52017:24)
    at Emitter._deliver (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12271:26)
    at Emitter.fire (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12300:22)
    at MutableToken.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12686:35)
    at CancellationTokenSource.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12733:29)
    at Object.dispose (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12754:40)
    at dispose (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:5534:27)
    at DisposableStore.clear (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:5617:17)
    at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:22304:19
    at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:22297:17
```

### Actual (Problematic) Behavior

Error appears in the browser console.

### Expected Behavior

There should be nothing in the browser console.

**Comment by EvanWiederspan** [comment]
I see this happening in 0.52.2 as well, is there a fix? The uncaught exception is causing my Jasmine tests to fail
