### ISSUE TITLE
[Bug]  Rapid pasting raises a `Canceled: Canceled` exception

### ISSUE THREAD

**Issue by OfekShilon** [microsoft/monaco-editor#4776]
### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

It is reproducible in monaco playground, but the actual monaco code is immaterial.  You can use the default https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.0#example-creating-the-editor-hello-world

### Monaco Editor Playground Code

```typescript

```

### Reproduction Steps

At the preview pane, copy some text with Ctrl+C and then repeatedly paste by holding down Ctrl+V:

![Image](https://github.com/user-attachments/assets/461b1847-79b0-4e2c-9584-bc6787fb4b5b)

### Actual (Problematic) Behavior

Don't mind the clipboard-CORS permission issue. The monaco related problem is evident in the stack:
```
async.ts:28  Uncaught (in promise) Canceled: Canceled
    at UniqueContainer.value (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:51766:24)
    at Emitter._deliver (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12271:26)
    at Emitter._deliverQueue (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12282:22)
    at Emitter.fire (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12305:22)
    at MutableToken.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12686:35)
    at CancellationTokenSource.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:12733:29)
    at Object.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:51780:24)
    at CopyPasteController.handlePaste (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:174859:42)
    at HTMLDivElement.<anonymous> (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:174757:91)
```

### Expected Behavior

No exception.

### Additional Context

This exception is often encountered in compiler-explorer sentry logs.  Currently reported here: https://github.com/compiler-explorer/compiler-explorer/issues/7181

**Comment by OfekShilon** [comment]
ping @hediet ?

**Comment by OfekShilon** [comment]
@jrieken  [here](https://github.com/microsoft/vscode/issues/204703#issuecomment-2527563684) you asked for a repro. What do you make of this one?

**Comment by cx-shahar-kazaz** [comment]
Also getting this error on some scenarios 👍

**Comment by OfekShilon** [comment]
@jrieken @hediet, gentle ping after 0.5Y.

**Comment by OrReuben** [comment]
any update here?
