### ISSUE TITLE
[Bug] TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from app/monaco/vs/language/json/jsonWorker.js

### ISSUE THREAD

**Issue by cintaccs** [microsoft/monaco-editor#4778]
### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript

```

### Actual (Problematic) Behavior

editor.main.js:9 Uncaught Error: **Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from app/monaco/vs/language/json/jsonWorker.js**

**TypeError: Failed to parse URL from app/monaco/vs/language/json/jsonWorker.js**
    at A.load (workerMain.js:6:13847)
    at n.load (workerMain.js:6:11936)
    at r (workerMain.js:8:9341)
    at f._loadModule (workerMain.js:8:9469)
    at f._resolve (workerMain.js:9:452)
    at f.defineModule (workerMain.js:8:5564)
    at f._relativeRequire (workerMain.js:8:6188)
    at a (workerMain.js:8:8519)
    at workerMain.js:29:82407
    at new Promise (<anonymous>)
    at A.load (workerMain.js:6:13847)
    at n.load (workerMain.js:6:11936)
    at r (workerMain.js:8:9341)
    at f._loadModule (workerMain.js:8:9469)
    at f._resolve (workerMain.js:9:452)
    at f.defineModule (workerMain.js:8:5564)
    at f._relativeRequire (workerMain.js:8:6188)
    at a (workerMain.js:8:8519)
    at workerMain.js:29:82407
    at new Promise (<anonymous>)
    at editor.main.js:9:12

### Additional Context

This is 52.2 using Chrome latest - using  

import loader from '@monaco-editor/loader';

"@monaco-editor/loader": "^1.4.0",

**Comment by cintaccs** [comment]
the worker loads used to work in 0.50.0

**Comment by philipsens** [comment]
Did it fail to parse because the page gives a 404?

**Comment by cintaccs** [comment]
I dont see any 404 - however I saw something....

Seems to be related to CSSMODE and JSONMODE ... ??

<img width="1293" alt="Image" src="https://github.com/user-attachments/assets/46c179b4-9d3a-400d-9115-059acc8d8fd9" />


<img width="1310" alt="Image" src="https://github.com/user-attachments/assets/044c37af-3da4-4ff2-970a-418cf38bc1ad" />
<img width="1309" alt="Image" src="https://github.com/user-attachments/assets/b7bea6d0-9de5-4370-85f9-4737758172cb" />

when using it for SQL
 <img width="1262" alt="Image" src="https://github.com/user-attachments/assets/2dae65fd-8932-49d5-ad0a-5c270133a780" />

there is no issue

**Comment by cintaccs** [comment]
> it's ok when use sql, but show this error when load htmlworker.js

not sure I understand... What I see is that it fails with jsonmode and cssmode ... which I assume will try to load workers ... however when using "sql" mode - it is using the workermain and have no loading worker issues...

**Comment by serdarciplak** [comment]
I have the same issue.

It happens when a relative path is used for `paths.vs` as in [this sample](https://github.com/microsoft/monaco-editor/blob/HEAD/docs/integrate-amd.md).
```js
require.config({ paths: { vs: 'monaco-editor/min/vs' } });
```

Using an absolute path fixes the issue.
```js
require.config({ paths: { vs: 'http://localhost:5000/monaco-editor/min/vs' } });
```

Looks like relative paths are broken somewhere between `0.50.0` and `0.52.0`. Can we get a fix for this soon, or should we use a workaround like manually adding `document.baseURI` as a prefix to the path?

**Comment by 1aron** [comment]
It works for me:
```ts
loader.config({
    paths: {
        vs: window.location.origin + '/monaco-editor/vs'
    }
})
```

**Comment by cintaccs** [comment]
> It works for me:
> 
> loader.config({
>     paths: {
>         vs: window.location.origin + '/monaco-editor/vs'
>     }
> })

Thanks for the tip!

I had to include the path as well - then it seems to work also for me! Seems less solid though ...

```
const pathParts = window.location.pathname.split('/').filter(part => part); 

loader.config({
    paths: {vs: window.location.origin + '/' + pathParts[0] + '/app/monaco/vs'}
});

```

**Comment by JMGomes** [comment]
I have the same issue, about being unable to load jsonWorker.js.

I'm using angular with this library: https://www.npmjs.com/package/ngx-monaco-editor-v2

Any advice?

**Comment by MitkoTschimev** [comment]
> I have the same issue, about being unable to load jsonWorker.js.
> 
> I'm using angular with this library: https://www.npmjs.com/package/ngx-monaco-editor-v2
> 
> Any advice?

You can set it as baseUrl

```
export const monacoConfig: NgxMonacoEditorConfig = {
  baseUrl: window.location.origin + "/assets/monaco/min/vs",
  ...
```

And load it in angular with
```ts
importProvidersFrom(MonacoEditorModule.forRoot(monacoConfig))
```

**Comment by toiyabe** [comment]
I have this same issue, but from another file. I started having this problem after upgrading to 52.2.

Uncaught Error: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from /lib/monaco-editor/min/vs/language/html/htmlWorker.js

The patch suggested by @1aron worked for me:

`
loader.config({
    paths: {
        vs: window.location.origin + '/monaco-editor/vs'
    }
})
`

**Comment by Infern1** [comment]
> > I have the same issue, about being unable to load jsonWorker.js.
> > I'm using angular with this library: https://www.npmjs.com/package/ngx-monaco-editor-v2
> > Any advice?
> 
> You can set it as baseUrl
> 
> ```
> export const monacoConfig: NgxMonacoEditorConfig = {
>   baseUrl: window.location.origin + "/assets/monaco/min/vs",
>   ...
> ```
> 
> And load it in angular with
> 
> importProvidersFrom(MonacoEditorModule.forRoot(monacoConfig))

Is the case for standalone components? According the description I should use: `MonacoEditorModule.forRoot(monacoConfig)`  for NgModule?

**Comment by Flysky12138** [comment]
work in 0.51.0 error in 0.52.0

**Comment by arianox** [comment]
I'm running into the same issue. Has anyone found a way to combine the workaround with base href? Would appreciate any insights or solutions!

**Comment by szilardd** [comment]
> > I have the same issue, about being unable to load jsonWorker.js.
> > I'm using angular with this library: https://www.npmjs.com/package/ngx-monaco-editor-v2
> > Any advice?
> 
> You can set it as baseUrl
> 
> ```
> export const monacoConfig: NgxMonacoEditorConfig = {
>   baseUrl: window.location.origin + "/assets/monaco/min/vs",
>   ...
> ```
> 
> And load it in angular with
> 
> importProvidersFrom(MonacoEditorModule.forRoot(monacoConfig))

thanks!

it also works like this in `app.config.ts`:

```ts
import { provideMonacoEditor } from 'ngx-monaco-editor-v2';

export const appConfig: ApplicationConfig = {
    providers: [
        provideMonacoEditor({ baseUrl: window.location.origin + '/assets/monaco/min/vs' }),
    ]
}
```

**Comment by aceArt-GmbH** [comment]
This seems fixed in 0.54 for me. Anyone else?
