### ISSUE TITLE
_textSpanToRange is not a function/object doesn't support property or method

### ISSUE THREAD

**Issue by wiredprairie** [Microsoft/monaco-editor#57]
Steps to reproduce:

1. Using the [Demo](https://microsoft.github.io/monaco-editor/) web page, select `TypeScript`. 
2. Right click on a symbol such as `GameOfLife` and select `Go to symbol`. 

In the console (or an alert box depending on the browser), the following crash will happen:

    TypeError: this._textSpanToRange is not a function
        at t (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/typescript/src/mode.js:7:12226)
        at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/typescript/src/mode.js:7:12443
        at Array.forEach (native)
        at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/typescript/src/mode.js:7:12416
        at Object.g [as _notify] (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:33:4544)
        at Object.enter (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:33:8122)
        at _run (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:33:9950)
        at _completed (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:33:9391)
        at Object.g [as _notify] (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:33:4544)
        at Object.enter (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js:33:8122)

Locally, I'm using 0.5.1 of the editor, and this issue happens in Chrome, Edge, and IE. (I've not tested with FireFox).

**Comment by jrieken** [comment]
got fixed
