### ISSUE TITLE
Unable to get property 'kind' of undefined or null reference

### ISSUE THREAD

**Issue by salileo** [Microsoft/monaco-editor#711]
monaco-editor version: 0.10.0
Steps or JS usage snippet reproducing the issue:
Seeing the following error randomly during usage of the control -

```
TypeError: Unable to get property 'kind' of undefined or null reference
   at _t (monaco-editor/0.10.0/min/vs/language/typescript/lib/typescriptServices.js:33:4916)
   at r (monaco-editor/0.10.0/min/vs/language/typescript/lib/typescriptServices.js:59:24710)
   at C (monaco-editor/0.10.0/min/vs/language/typescript/lib/typescriptServices.js:65:26579)
   at D (monaco-editor/0.10.0/min/vs/language/typescript/lib/typescriptServices.js:65:26939)
   at x (monaco-editor/0.10.0/min/vs/language/typescript/lib/typescriptServices.js:65:26362)
   at e.prototype.getOccurrencesAtPosition (monaco-editor/0.10.0/min/vs/language/typescript/src/worker.js:9:3031)
   at e.prototype.fmr (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:149450)
   at t.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110446)
   at handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110099)
   at e.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:108181)
message: Unable to get property 'kind' of undefined or null reference
```

**Comment by alexandrudima** [comment]
Duplicate of #621
