### ISSUE TITLE
Unable to get property 'join' of undefined or null reference

### ISSUE THREAD

**Issue by salileo** [Microsoft/monaco-editor#712]
monaco-editor version: 0.10.0
Steps or JS usage snippet reproducing the issue:
Seeing the following console error during random usage of the console -

TypeError: Unable to get property 'join' of undefined or null reference
   at e.prototype.getText (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:141068)
   at t.prototype.getValue (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:143626)
   at e.prototype._getTextDocument (monaco-editor/0.10.0/min/vs/language/json/jsonWorker.js:9:28452)
   at e.prototype.doHover (monaco-editor/0.10.0/min/vs/language/json/jsonWorker.js:9:27801)
   at e.prototype.fmr (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:149450)
   at t.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110446)
   at handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110099)
   at e.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:108181)
   at e.prototype.handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:107706)
   at t.prototype.onmessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110172)
message: Unable to get property 'join' of undefined or null reference

**Comment by alexandrudima** [comment]
deminified stack trace:

TypeError: Unable to get property 'join' of undefined or null reference
[   at e.prototype.getText (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:141068)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/mirrorModel.ts#L52)
[   at t.prototype.getValue (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:143626)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/services/editorSimpleWorker.ts#L100)
   at e.prototype._getTextDocument (monaco-editor/0.10.0/min/vs/language/json/jsonWorker.js:9:28452)
   at e.prototype.doHover (monaco-editor/0.10.0/min/vs/language/json/jsonWorker.js:9:27801)
[   at e.prototype.fmr (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:149450)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/services/editorSimpleWorker.ts#L507)
[   at t.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110446)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L329)
[   at handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110099)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L311)
[   at e.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:108181)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L157)
[   at e.prototype.handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:107706)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L119)
[   at t.prototype.onmessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110172)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L316)

**Comment by alexandrudima** [comment]
`MirrorModel._lines` is never assigned null or undefined, so this stack trace does not make sense to me...
