### ISSUE TITLE
Uncaught Error in JSON Worker when using JSON Schema with ENUM type

### ISSUE THREAD

**Issue by foxable** [Microsoft/monaco-editor#954]
monaco-editor version: 0.13.1
Browser: Chrome (also Firefox, IE and Edge)
OS: Windows 10

Steps reproducing the issue:

1. Copy the following snippet and paste it into the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html):
```
var id = "foo.json";

monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	schemas: [{
        uri: "http://myserver/foo-schema.json",
        fileMatch: [id],
        schema: {
            "enum": ["item1", "item2"]       
        }
    }]
});

var model = monaco.editor.createModel("{}", "json", id);

monaco.editor.create(document.getElementById("container"), {
    model: model
});
```
2. Press "Run"
3. Set the cursor between the two curly braces
4. Type `"`

This results in the following exception:
```
editor.main.js:158 Uncaught [Error: Cannot read property 'type' of undefined
    at I (https://microsoft.github.io/monaco-editor/…]0: Error: Cannot read property 'type' of undefined
    at I (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:38625)
    at I (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:38773)
    at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:50063
    at E (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:50894)
    at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:49101
    at Array.forEach (<anonymous>)
    at o (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:49046)
    at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:50013
    at E (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:50894)
    at e.getMatchingSchemas (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/language/json/jsonWorker.js:7:40378)length: 1__proto__: Array(0)
(anonymous) @ editor.main.js:158
setTimeout (async)
unexpectedErrorHandler @ editor.main.js:158
e.onUnexpectedError @ editor.main.js:159
i @ editor.main.js:157
(anonymous) @ editor.main.js:158
(anonymous) @ editor.main.js:158
setTimeout (async)
(anonymous) @ editor.main.js:158
dispatchEvent @ editor.main.js:140
v @ editor.main.js:143
f @ editor.main.js:142
_error @ editor.main.js:147
e._handleMessage @ editor.main.js:254
e.handleMessage @ editor.main.js:253
(anonymous) @ editor.main.js:254
worker.onmessage @ editor.main.js:290
```

**Comment by aeschli** [comment]
This issue git fixed in jsonc-parser. It will be available in the next version of the monaco-editor.
