### ISSUE TITLE
Can not run in jest

### ISSUE THREAD

**Issue by liuyangc3** [Microsoft/monaco-editor#996]
monaco-editor version: 0.13.1
Browser: Chrome
OS:  Windows 10
Steps or JS usage snippet reproducing the issue:

test.test.js
```
import 'monaco-editor/esm/vs/editor/browser/controller/coreCommands.js';
import 'monaco-editor/esm/vs/editor/contrib/find/findController.js';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api.js';
import 'monaco-editor/esm/vs/basic-languages/sql/sql.contribution.js';

it('renders without crashing', () => {
  const div = document.createElement('div');
  monaco.editor.create(div, {
    value: "",
    language: "sql"
  });
});
```

output
```
Test suite failed to run

    C:\Users\web\test\node_modules\monaco-editor\esm\vs\editor\browser\controller\coreCommands.js:16
    import { Position } from '../../common/core/position.js';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/Editor.test.js:1:103)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by alexandrudima** [comment]
Well, it looks like you are trying to load the ESM form of the editor in a JS engine which does not understand ESM.

**Comment by liuyangc3** [comment]
you re right , https://github.com/facebook/jest/issues/4842

**Comment by omril1** [comment]
Did you manage to solve it?

I tried running tests with jest, and tried setting different values to `moduleNameMapper` and `transform`, but couldn't manage to run it in jest.

**Comment by buybackoff** [comment]
This thread with `moduleNameMapper` fix helped me: https://github.com/superRaytin/react-monaco-editor/issues/133#issuecomment-403960502

**Comment by garytryan** [comment]
I think I've found a solution. I've posted an article here with details https://medium.com/hired-engineering/setting-up-monaco-with-jest-e1e4c963ac
